db:
  image: mysql/mysql-server:5.7
  env_file: .docker-environment
  ports:
    - "3306:3306"
web:
  build: .
  env_file: .docker-environment
  volumes:
    - .:/subpop
  ports:
    - "3000:3000"
  links:
    - db
  command: bundle exec rails server -b 0.0.0.0

delayedjob:
  build: .
  links:
    - db
  volumes:
    - .:/subpop
  env_file: .docker-environment
  command: bundle exec rake jobs:work
