db:
  image: mysql/mysql-server:5.7
  env_file: .docker-environment
  ports:
    - "3306:3306"
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  env_file: .docker-environment
  volumes:
    - .:/subpop
  ports:
    - "3000:3000"
  links:
    - db
