# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e740ab41ed05eee950ec788ac0a0f9ab4f630111a961936b62a5385534f101b397a8e255e2b2d476cd74c363ae29fe5d41cc918d333c35e92f5c8b46f234c98

test:
  secret_key_base: 20047e2c74ec122ee34cb3eeb8cd7301b92f9049462adbac866a81dda4f3e46d42518d315105bfeced52355354ffbfe26f573e545fc8678675bf14fb5c029ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SUBPOP_SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SUBPOP_SECRET_TOKEN'] %>